// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdmhwqwikmlbiudtbkeq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkbWh3cXdpa21sYml1ZHRia2VxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNTYyNzgsImV4cCI6MjA2ODkzMjI3OH0.55pcDktFmEHQcoISgUwfV_HSu8o9B_FAdXvOOyw-VtY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});